# Try:
# a = int(input("Hey, enter your name:"))
# print(a)
# except Exception as e:
# print(e)

try:
    a = input("Hey, enter your number : ")
    print(a)
except Exception as e:
    print(e)
else:
    print("Thank you")
''' Pyhton can handle the exception using try and except block statement  '''